### ISSUE TITLE
status checking

### ISSUE THREAD

**Issue by ybdesire** [appknox/androguard#5]
Very happy to know there is Python 3 support for Androguard. Thanks a lot for this branch.

* Is this the stable release?

* Any test have been passed on this branch ?

**Comment by subho007** [comment]
@ybdesire this is kind of stable and production ready. Few more fixes are on the way. Test-suites are not yet checked. Any PR is welcome :)

**Comment by subho007** [comment]
you can install it by `pip3 install ak-androguard`
